name: run-api-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Check injected secrets
      run: |
        echo "BASE_URL=$BASE_URL"
        echo "USER_NAME=$USER_NAME"
        echo "PASS_WORD=$PASS_WORD"
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASS_WORD: ${{ secrets.PASS_WORD }}

    - name: Run API Tests
      run: npm test
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASS_WORD: ${{ secrets.PASS_WORD }}
